blank_issues_enabled: false
contact_links:
  - name: ❓ Support question
    url: https://github.com/llaville/phpunit-LoggerTestListener/discussions/new
    about: Please open a new discussion instead. Thank you.
